name: python-suite
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.11.9
  - pip>=23.0
  - numpy=1.23.5
  - pandas>=2.0
  - scipy>=1.10
  - matplotlib>=3.7
  - pingouin>=0.5.3
  - pyqt  # Replaced 'pyqt5>=5.15' with 'pyqt' to use the available package from conda channels
  - statsmodels>=0.14
  - seaborn>=0.12
  - scikit-learn>=1.3
  - pyyaml>=6.0
  - wxpython>=4.2
  - configparser>=5.3
  - requests>=2.31
  - pillow>=10.0
  - pip:
    - psychopy==2023.1.3
    - pycap>=2.0.0
    - keyboard>=0.13
    - imageio>=2.31
    - json5>=0.9
    - moviepy>=1.0
    - pygame==2.6.0
    - psychtoolbox==3.0.19.14
    - pypiwin32==223
    - soundfile==0.12.1
    - pywin32==306
    - imageio-ffmpeg==0.5.1
    - ffpyplayer==4.5.1
    - pyglet==1.4.11
    - python-vlc==3.0.11115

variables:
  PSYCHOPY_NOTIFICATION_CLICK: 'False'
  PYGAME_HIDE_SUPPORT_PROMPT: 'hide'